# Generated by Django 5.1.2 on 2024-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='name_he',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='hPrP37S3vv0tutEzzCIELaBoIoaVRbNjnz0EUL1kLhWDj5Ee3sgmCgqbIfZ02JJa', max_length=64, unique=True),
        ),
    ]
