# Generated by Django 5.1.2 on 2024-11-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0002_rename_name_en_competition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cggroup',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeguru.competition'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='Kp6Z7eZCmV6ZEXwzoG6Fi1xIvscsh9vJtkrIOr5mcWa0reauRDyehhj6831CoIiV', max_length=64, unique=True),
        ),
    ]
