# Generated by Django 5.1.2 on 2024-11-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0004_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cggroup',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeguru.competition'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='9DLD67oWBfvieYpycV4ksEJwiF6T2rsGsHSxnoxWaw687vDNxKyHxFhhBffiUlKO', max_length=64, unique=True),
        ),
    ]
