# Generated by Django 5.1.3 on 2024-11-12 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeguru", "0007_competition_survivor_signature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="survivor_signature_value",
        ),
        migrations.AddField(
            model_name="competition",
            name="survivor_signature_value",
            field=models.PositiveIntegerField(
                default=144,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)],
            ),
        ),
    ]
