# Generated by Django 5.1.3 on 2024-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0008_alter_competition_survivor_signature_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='survivor_max_length',
            field=models.PositiveIntegerField(default=512),
        ),
    ]
