// Generates agent2/night/cards.json: 50 performance cards (A001-A050) and 50 defense cards
// (B051-B100 = 10 domains x 5 roles, role-major so waves progress verify -> measure -> counter -> fix -> cost).
import fs from "node:fs";
const A = [
  "Startup cost of warrior A: remove redundant instructions (e.g. `and dx,0 / or dx,0FFBh` -> direct mov, the jmp to the next line, the dead zombie_entry/zombie_scan block) and measure whether earlier entry into the replicator helps. Keep zom20a capture semantics.",
  "Startup cost of warrior B: shorten/reorder B's initializer (cell writes, INT87 placement, quantizer) so the replicator starts earlier, without breaking zombie_entry (which reuses B code and the get_ip arithmetic).",
  "Timing of A's zom20a capture: move A's INT87 earlier or later relative to the cell copy; check the race against competitors who also target zom20a; screen.",
  "First-generation geometry: A gap 100h / B gap 600h and first copy CX values; try a few principled alternatives (e.g. equalize first-generation length).",
  "A/B start synchronization: adjust startup lengths so A and B enter steady state in a controlled phase relation; measure partner interference.",
  "Template copy counts: CX 9 vs 8 for first and later rebuilds in A and B (B uses CX 8 in its first copy). Verify mechanically (extra/short copied bytes) then screen.",
  "A's step/stack motion (BP 4400h / DX 4000h): evaluate alternatives that keep full 64-position coverage (gcd with 10000h = 400h) and trail length 400h.",
  "B's step (BP 2C00h / DX 2400h) vs V4's 2800h/2000h (only 32 positions) vs other full-coverage steps; V4 differs from V6 only here.",
  "Band phases: A phase 2Ch, B phase 10h, zombie phases 2000h/3400h (added to AX); explore separations that minimize A/B/zombie lane overlap.",
  "Quantization: divisor 3Ch on the load high byte; try other band schemes (different divisor, mask) that spread A, B and zombies better.",
  "Lattice undercut: FAR_SEG 0FFBh (in-page 52h). Test 0FFAh (42h) / 0FF9h (32h) for BOTH warriors and captured zombies (all streams same lattice). Known: 10h below a crowd wins vs that crowd; check the cost on the plain field.",
  "Separate lattice for captured zombies only (they run B's phoenix code) - can zombies live on an offset lattice without crossfire on A/B? Measure.",
  "Captured zombies' motion: they run B's phoenix (DX 2400h, BP 2C00h, gap 600h). Give zombies their own step/gap tuned for speed-2 processes.",
  "A/B lockstep separation: same step for A and B with a fixed relative offset (e.g. 8000h) using team-shared memory to coordinate the band; measure partner collisions and score.",
  "Trail length per generation (BP-DX=400h): test 300h/500h/800h variants (keep coverage), considering anchor dwell exposure vs rebuild overhead.",
  "Stack/anchor alignment: verify SP and anchor residues for all streams (A, B, zombies) and test whether any stream currently misaligns (rebuild failures).",
  "Anchor encoding: `FF 1F` call far [bx] vs `FF 18` [bx+si] vs `FF 1C` [si] etc. - effect of which ModRM byte opponents' writes turn benign/fatal; measure.",
  "Anchor redundancy: write a recovery word after the anchor (e.g. a second `FF 1F`) so common single-byte ModRM hits (FF CC = dec sp) fall through into a valid call; check rebuild still works.",
  "Worker shortening: fewer instructions in the 18-byte worker (e.g. LES DI,[BX], keep CX, avoid XOR SI) to cut rebuild exposure; verify template/copy-count consistency.",
  "Worker instruction order: reorder dependency-safe worker instructions to shrink the exposed window during rebuild; measure.",
  "Kill pattern of our trail: the pushed CS word is FB 0F (STI; invalid). Explore FAR_SEG values whose low byte is immediately fatal (F6/F7 /1 are invalid in v6) while keeping a sane lattice; measure lethality vs cost.",
  "Private memory layout: template at SS:0, cells 2C0h/280h; check whether cell/template positions interact with REP copy overrun (CX words copied beyond the template) and fix if harmful.",
  "Rebuild exposure: the anchor+1..+22 window; try placing or splitting the worker to reduce overlap with incoming trails; prototype carefully.",
  "Remove A's dead hunter code and use freed bytes for something useful (e.g. anchor recovery or a decoy) - measure each separately.",
  "INT 86h for A/B (currently unused, 2 charges each): where could 256-byte bombs help without self-damage (e.g. ahead of own first trail, around zombie positions)? Prototype, screen.",
  "INT 86h by captured zombies (each has 2 charges): use them at capture time (a zombie knows its own code location) to wipe something useful; screen.",
  "zrl03-style two-step b/d capture without planting decoys: make B's first search kill the top decoy and the second capture the live tail, using V6's cell layout; check vs zombie competitors.",
  "Fallback counter-bomb of the captured b/d zombie: `0E 07 0E 17` -> CC. Measure alternative 4-byte targets present in many 2025/2024 initializers (scan the binaries) and pick by field data.",
  "NRG economics: any place where NRG (9B 9B) pays off (startup? zombies? worker?) given decay 1 per 5 rounds; prototype at most one well-reasoned variant.",
  "INT 87h smart-bomb aimed at MOVSW-family anchors or workers (e.g. their rebuild template bytes) using a spare charge; verify target bytes in the binaries first.",
  "Defensive INT 86h: overwrite our own abandoned initializer to remove signatures, or bomb regions opponents use to locate us; measure.",
  "zom20c capture: its live loop is the 3rd of 8 identical copies (a forward search hits copies 0,1,2). Is there any charge budget/pattern that captures it? Prototype if feasible.",
  "Capture the second (lower) zom20b/d: compute the charge budget (A, B, zom20a, b/d = 4 charges); try a reassignment that yields an extra capture without losing the counter-bomb.",
  "Captured-process roles: all captured zombies become replicators. Try giving one captured zombie a different role (e.g. revive the trail hunter only for zombies, or a bomber) and measure.",
  "Lane separation for captured zombies (speed 2 laps survivors): choose zombie phases/steps that minimize their crossings of A/B anchors; verify with a trace.",
  "Make zom20a capture happen earlier (it depends on A's INT87 timing and on [4A17h] being written by B); measure capture rate (trace) and score.",
  "Hook cell robustness: [4A17h] is a fixed shared cell (the V4/V6 family uses it too). Try a less collision-prone cell or a double-pointer scheme; measure vs lead_V6/lead_V4 threats.",
  "zom20a capture robustness vs mimics: E2 F2 81 C3 also appears in Grindo/callfart/AnotherBit. Can a more specific pattern or search start avoid mimics? Measure vs zomb_* threats.",
  "b/d capture search parameters: start DI, direction, pattern choice; measure capture rate and score vs zombie competitors.",
  "Use leaked zombie information (zom20b/d write fixed addresses x612h/x226h; zom20c's column) to locate zombies precisely; prototype a direct-write capture if feasible.",
  "Measure A/B partner trail collisions in the base (trace) and test a separation fix.",
  "Captured zombies vs partners: do zombie trails kill A/B anchors or workers? Trace and fix (family/lattice consistency).",
  "Team-shared memory communication: B reads A's band (or vice versa) to pick a complementary lane; prototype a minimal protocol.",
  "Self-harm at startup: own writes ([4A17h], [5D13h], [9769h], INT87 replacements, stosw) hitting own or partner code; check with a trace and fix.",
  "Pointer cell vs stack: verify no SP/stack interaction can corrupt the private pointer cells or the template in any stream (zombies have their own SS).",
  "Hybrid pair: one warrior from zchain4 (strong on the plain 2025 field) + one from the base (robust vs leaders). Check family/lattice compatibility (zchain4 is also on lattice 52h, FAR_SEG 0FFBh) and zombie-cell interplay; screen.",
  "Graft zchain4's zombie-chain idea (captured b/d captures zom20a with 41 93 E2 F2) into the base's charge budget if it frees a charge for another use; screen.",
  "Graft combo_zrl03 ideas (decoy-immune capture pattern 0F EB F9 CC with the CC-high-byte cell trick) into the base without planting decoys; screen and threat-test vs lead_V6.",
  "Independent idea of your choice inside the current architecture - justify it with engine facts and prior data, prototype, screen.",
  "Radical new strategy family (not a far-call replicator tweak) prototyped quickly; screen once; report honestly even if it loses.",
];
const D = [
  "Collision with other replicators, especially MOVSW-family trails hitting our MOVSB-family anchors (FF A5).",
  "Zombie competition and zombie mimics (HRZ_Grindo_Holics, GSA_callfart, AVI_AnotherBitInTheWall).",
  "Zombie theft through fixed hook cells (5D13h, 9769h, 4A17h): when are cells read, can a write redirect our captured zombies?",
  "Decoys that waste our INT87 searches (combo_zrl03 planted EB F9 at FFECh/FFE8h; zombie mimic copies).",
  "Lattice height/offset differences between replicator families (undercut by 10h-60h).",
  "Signature attacks on our initializer bytes via INT87 (New_Best-style 4-byte search and replace on published Survivor code).",
  "Trail scanners / anchor hunters that detect far-call trails and bomb the anchor (V6's own zombie_scan is one such design).",
  "Dense bombers (IND_BRA-style sparse CC) and early INT86 heavy bombs before we are established.",
  "Self-harm: A/B partner collisions, captured-zombie trails hitting survivors, own startup writes.",
  "New threats, combined attacks, and fields with several teams of the same counter family (2-3 copies).",
];
const R = [
  ["R1-verify", "Verify the mechanism in the CURRENT base and classify it (verified-in-current / verified-in-other / hypothesis / not-reproduced) with a trace or threat job; point to the exact bytes/instructions involved."],
  ["R2-measure", "Measure prevalence and impact in realistic fields: which opponents in the 2025/2024 pools exhibit it (scan binaries with dis86 or byte search) and how many points/battle it costs the base (threat jobs on the relevant library keys)."],
  ["R3-counter", "Write a NEW counter-code (asm in your scratch, <=256 B per warrior, file names counterA.asm/counterB.asm) that exploits this weakness on purpose; measure it against the base with threat jobs (also --copies 2/3). It becomes a test case for fixes."],
  ["R4-fix", "Design and test a defensive fix in the base: screen it (general cost) and threat-test it on the relevant counters (library keys and counter-codes other agents left in agent2/night/scratch/*/counter*.asm). Keep the fix documented even if not promotable."],
  ["R5-cost", "Audit fixes proposed for this weakness so far (agent2/night/FINDINGS.md and other agents' scratch reports): pick the best, test its general cost and its interaction with another promising change (combination screen), and recommend promote / do-not-promote."],
];
const cards = A.map((card, i) => ({ id: `A${String(i + 1).padStart(3, "0")}`, group: "A-performance", card }));
let n = 51;
for (const [role, text] of R) D.forEach((d, di) => { cards.push({ id: `B${String(n).padStart(3, "0")}`, group: "B-defense", domain: di + 1, role, card: `Domain ${di + 1}: ${d} Role ${role}: ${text}` }); n++; });
fs.writeFileSync("agent2/night/cards.json", JSON.stringify(cards, null, 1) + "\n");
console.log(cards.length, cards[0].id, cards[50].id, cards[99].id);
