import fs from 'node:fs';
import path from 'node:path';
const root='C:/Maor/CodeGuru/corewars8086-lab';
const results=path.join(root,'.arena/v6-cooperative-20261003/results');
const old=JSON.parse(fs.readFileSync(path.join(results,'kphldef-20261004-confirm-counters-persistent.json')));
const next=JSON.parse(fs.readFileSync(path.join(results,'kphldef-20261004-adapted-guard-counter-persistent.json')));
function total(runs,arm){const xs=runs.filter(r=>r.arm===arm),points=xs.reduce((s,r)=>s+r.team,0),battles=xs.reduce((s,r)=>s+r.battles,0);return{points,battles,pointsPerBattle:points/battles};}
const oldRuns=old.runs.filter(r=>Object.keys(r.opponents)[0]==='Counter_boot_hunter');
const pairs=next.runs.map(r=>{const before=oldRuns.find(x=>x.arm===r.arm&&x.cohort===r.cohort&&x.seed===r.seed);if(!before||before.battles!==r.battles)throw Error('Non-matching counter experiment');return{arm:r.arm,cohort:r.cohort,seed:r.seed,originalPatternPoints:before.team,adaptedPatternPoints:r.team};});
const report={schema:'KPHLGuard-adversarial-followup-v1',generatedAt:new Date().toISOString(),decision:'NOT_ROBUST_AGAINST_ADAPTED_SIGNATURE_HUNTER',originalPattern:{hex:'160731FF',base:total(oldRuns,'base'),KPHLGuard:total(oldRuns,'KPHLGuard')},adaptedPattern:{hex:'160729FF',base:total(next.runs,'base'),KPHLGuard:total(next.runs,'KPHLGuard')},pairs,counterAudit:JSON.parse(fs.readFileSync(path.join(root,'.arena/kphl-defense-20261004/adaptive-counter/protocol.json'))).audit,interpretation:'The candidate removes a known fixed signature without changing timing, but creates an equally targetable replacement. A one-byte adjustment of the search constant in each opposing warrior reverses the entire 138-versus-0 outcome on the identical four seeds. This is signature camouflage, not removal of the underlying pre-bootstrap attack surface. No broad-field regression was observed in the earlier field test, but no unconditional improvement or robust immunity is established.',disposition:'Research candidate only. Do not promote as robust defense or claim guaranteed improvement. Release source hashes remain the same; original narrow positive result remains valid but incomplete.',results:{original:path.relative(root,path.join(results,'kphldef-20261004-confirm-counters-persistent.json')),adapted:path.relative(root,path.join(results,'kphldef-20261004-adapted-guard-counter-persistent.json'))}};
fs.writeFileSync(path.join(root,'.arena/kphl-defense-20261004/adaptive-counter/report.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({decision:report.decision,originalPattern:report.originalPattern,adaptedPattern:report.adaptedPattern},null,2));
