# Generated by Django 5.1.2 on 2024-11-06 13:30

import django.core.validators
import django.db.models.deletion
import war.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeguru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.competition')),
                ('required_riddles', models.ManyToManyField(blank=True, to='war.riddle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiddleSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle_solution', models.FileField(upload_to=war.models.riddle_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.cggroup')),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war.riddle')),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_of_survivors', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('zombie_mode', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.competition')),
                ('required_riddles', models.ManyToManyField(blank=True, to='war.riddle')),
                ('required_wars', models.ManyToManyField(blank=True, to='war.war')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_file', models.FileField(null=True, upload_to=war.models.asm_surv_upload, validators=[war.models.asm_max])),
                ('bin_file', models.FileField(upload_to=war.models.bin_surv_upload, validators=[war.models.bin_max])),
                ('result', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.cggroup')),
                ('war', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='war.war')),
            ],
        ),
    ]
