# Generated by Django 5.1.2 on 2024-11-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0003_alter_cggroup_competition_alter_invite_code'),
        ('war', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.competition'),
        ),
        migrations.AlterField(
            model_name='war',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.competition'),
        ),
    ]
