# Generated by Django 5.1.3 on 2024-12-07 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("war", "0003_alter_riddlesolution_riddle_solution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="war",
            name="survivor_numbering_start",
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
